apiVersion: v1
kind: Service
metadata:
  name: spring-boot-docker
  labels:
    expose: "true"
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer